- hosts:  hosts-oracle
  become: True
  become_user: root
  tasks:

  - name: Habilita o multilib_policy em /etc/yum.conf
    lineinfile:
     path: /etc/yum.conf
     regexp: '.*multilib_policy.*'
     insertafter: '^installonly_limit.*'
     line: 'multilib_policy=all'
     backup: yes

  - name: Instalar pacotes do SO
    yum: state=latest disable_gpg_check=yes  name="{{item}}"
    with_items:
      - nspr
      - libstdc++*
      - libgcc*
      - libc*
      - glibc.i686
      - nfs-utils
      - net-tools
      - ntp
      - vim
      - psmisc
      - bc
      - elfutils-libelf
      - elfutils-libelf-devel
      - fontconfig-devel
      - libXrender
      - libnsl
      - librdmacm
      - libibverbs
      - policycoreutils
      - policycoreutils-python-utils
      - smartmontools
      - binutils
      - compat-libcap1
      - compat-libstdc++-33
      - gcc
      - gcc-c++
      - glibc
      - glibc-devel
      - ksh
      - libgcc
      - libstdc++
      - libstdc++-devel
      - libaio
      - libaio-devel
      - libXext
      - libXtst
      - libX11
      - libXau
      - libxcb
      - libXi
      - make
      - sysstat
      - libXmu
      - libXt
      - libXv
      - libXxf86dga
      - libdmx
      - libXxf86misc
      - libXxf86vm
      - xorg-x11-utils
      - xorg-x11-xauth
    tags: pacotesSO

  - name: Cria diretorio bd_srvs_comum em /home/
    file: path=/home/bd_srvs_comum state=directory owner=oracle group=oinstall

  - name: Monta bd_srvs_comum e insere ponto de montagem no /etc/fstab
    mount:
      path: /home/bd_srvs_comum
      src: 172.29.69.10:/bd_srvs_comum
      fstype: nfs
      opts: "rw,bg,hard,suid,nointr,rsize=32768,wsize=32768,proto=tcp,actimeo=0,vers=3,timeo=600"
      state: mounted

  - name: Instalacao pacotes ASM
    include: 0401-instala_pacotes_asm_OL8.yml
    when: ansible_distribution=="OracleLinux"
    tags: asmlibs

  - name: Instalacao pacote preinstall da versão 19
    include: 06-instala_oracle-database-preinstall-19c.yml
    when: ansible_distribution=="OracleLinux"
    tags: oracle-preinstall
