- hosts:  hosts-oracle
  gather_facts: False
  become: True
  become_user: root
  tasks:

  - name: Cria diretorio bd_srvs_comum em /home/
    file: path=/home/bd_srvs_comum state=directory owner=oracle group=oinstall

  - name: Monta bd_srvs_comum e insere ponto de montagem no /etc/fstab
    mount: 
      path: /home/bd_srvs_comum
      src: 172.29.75.10:/bd_srvs_comum
      fstype: nfs
      opts: "rw,bg,hard,suid,nointr,rsize=32768,wsize=32768,proto=tcp,actimeo=0,vers=3,timeo=600"
      state: mounted
