---
- name: Habilita o multilib_policy em /etc/yum.conf
  lineinfile:
   path: /etc/yum.conf
   regexp: '.*multilib_policy.*'
   insertafter: '^installonly_limit.*'
   line: 'multilib_policy=all'
   backup: yes

- name: Instalar pacotes do SO para OL7
  yum: state=latest disable_gpg_check=yes  name="{{item}}"
  loop: "{{ pacotes7 }}"
  when: ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "7"
  tags: pacotesSO
  ignore_errors: yes

- name: Instalar pacotes do SO para OL8
  yum: state=latest disable_gpg_check=yes  name="{{item}}"
  loop: "{{ pacotes8 }}"
  when: ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "8"
  tags: pacotesSO
  ignore_errors: yes

- name: Instalar pacote OracleASM for OL7
  yum: 
    state: latest 
    disable_gpg_check: yes
    name: 
      - kmod-oracleasm.x86_64
      - oracleasm-support.x86_64
#     - oracleasmlib
#  with_items:
#    - kmod-oracleasm.x86_64 
#    - oracleasm-support.x86_64
#    - oracleasmlib
  when: ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "7"
  tags: install_asm

#- name: Instalar pacote OracleASM for OL8
#  yum: state=latest disable_gpg_check=yes  name="{{item}}"
#  with_items:
#    - oracleasm-support
#    - kmond-oracleasm
#    - oracleasmlib
#  when: ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "8"

- name: Instalar Oracle RDBMS PreInstall
  yum: state=latest disable_gpg_check=yes name=oracle-database-preinstall-19c

- name: Cria diretorio oinstall em /home/
  file: path=/home/oinstall state=directory owner=oracle group=oinstall

- name: Verifica se o storage está disponível
  wait_for:
    host: "{{interface_storage}}"
    port: 2049
    state: present
    timeout: 10

- name: Monta oinstall e insere ponto de montagem no /etc/fstab
  mount:
    path: /home/oinstall
    src: "{{interface_storage}}:/oinstall"
    fstype: nfs
    opts: "rw,bg,hard,suid,nointr,rsize=32768,wsize=32768,proto=tcp,actimeo=0,vers=3,timeo=600"
    state: mounted
